<div class="card mb-3 ">
  <img src="/img/exo2.jpg" class="album-card mx-auto d-block" alt="...">
  <div class="card-body">
    <h5 class="card-title text-center">BIOGRAFI EXO</h5>
    <p class="card-text">EXO (bahasa Korea: 엑소; sering ditulis sebagai EXO) adalah sebuah boy band Korea Selatan-Tiongkok berbasis di Seoul, dengan sembilan anggota: Suho, Baekhyun, Chanyeol, D.O., Kai, Sehun, Xiumin, Lay, dan Chen. Grup ini dibentuk oleh SM Entertainment pada tahun 2011 dan debut pada tahun 2012. Musik mereka memasukkan aliran seperti pop, hip-hop, dan R&B, dan juga aliran electronic dance music seperti house, trap, dan synth-pop. Exo merilis dan membawakan musik dalam Bahasa Korea, Mandarin, dan Bahasa Jepang. Grup ini menempati posisi lima besar sebagai selebritas paling berpengaruh dalam daftar Forbes Korea Power Celebrity tiap tahun dari 2014 sampai 2018, dan telah dijuluki "boy band terbesar di dunia" dan "kings of K-pop" oleh media.

Grup ini debut dengan 12 anggota yang dibagi menjadi dua sub-grup: EXO-K (Suho, Baekhyun, Chanyeol, D.O., Kai, and Sehun) dan EXO-M (Xiumin, Lay, Chen, dan para mantan anggota seperti Kris, Luhan, dan Tao). EXO-K dan EXO-M membawakan musik dalam Bahasa Korea dan Mandarin, masing-masing, sampai tahun 2014. Exo telah menjadi satu grup sejak saat itu, dengan tetap merilis dan membawakan musik dalam beberapa bahasa. Setelah keluarnya Kris, Luhan, dan Tao ditengan tuntutan hukum pada tahun 2014 dan 2015, grup ini tetap bertahan dengan sembilan anggota.Sejak tahun 2016, Chen, Baekhyun, dan Xiumin juga telah merilis musik dan tampil sebagai sebuah sub-unit bernama Exo-CBX. Semua anggota Exo juga mempunyai karier solo dalam bidang seperti musik, film, dan televisi.

Album pertama Exo XOXO (2013), yang menghasilkan hit terobosan "Growl", mendapat sukses kritis dan komersial. Lagu ini terjual lebih dari satu juta eksemplar, membuat Exo menjadi artis Korea terlaris dalam 12 tahun. Album-album dan EP berikutnya juga mendapat penjualan tinggi, dengan semua album studio masing-masing terjual lebih dari satu juta eksemplar. Album studio XOXO (2013), Exodus (2015) dan Ex'Act (2016), 'bersama dengan EP ketiga Exo Overdose (2014), memenangkan Exo beberapa penghargaan termasuk empat kemenangan berturut-turut masing-masing Disc Daesang di Golden Disc Awards, Album of the Year di Mnet Asian Music Awards dan Daesang award di Seoul Music Awards. Album keempat mereka The War (2017) menjadi album terlaris mereka sesudah dirilis, terjual lebih dari 1.6 juta eksemplar di Korea Selatan dan memenangkan penghargaan Artist of the Year kedua berturut-turut di Melon Music Awards, dan juga sebuah rekor penghargaan Album of the Year kelima berturut-turut di Mnet Asian Music Awards. Album kelima Exo Don't Mess Up My Tempo (2018) merupakan album dengan posisi tertinggi mereka di Billboard 200 AS, debut di nomor 23. Album ini juga merupakan album terlaris mereka dengan lebih dari 1.9 juta eksemplar di Korea Selatan.

Sejak tur utama Exo tahun 2014, grup ini telah tampil di lebih dari 100 konser dalam empat tur dan telah berpartisipasi dalam beberapa tur gabungan. Exo juga dikenal atas karya diluar musik,yang termasuk kesepakatan sponsor dengan merek-merek seperti Nature Republic dan Samsung, dan aksi-aksi amal seperti Smile For U, sebuah proyek gabungan dari SM Entertainment dan UNICEF yang dimulai pada tahun 2015, yang mana Exo terus ikut berpartisipasi.</p>
    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
  </div>
</div>